# Generated by Django 6.0.1 on 2026-01-15 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrueFlowapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterorders',
            name='total_price',
        ),
    ]
