# Generated by Django 6.0.1 on 2026-01-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrueFlowapp', '0002_remove_waterorders_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterorders',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
