# Generated by Django 6.0.1 on 2026-01-15 17:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrueFlowapp', '0003_waterorders_total_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WaterOrders',
            new_name='WaterOrder',
        ),
    ]
